### ISSUE TITLE
curtsies.formatstring.FmtStr.ljust loses colors

### ISSUE THREAD

**Issue by sebastinas** [thomasballinger/curtsies#62]
While looking at https://github.com/bpython/bpython/issues/439 I noticed that using `line.ljust` is not possible, since all color information is lost in the process. For example:

``` python
>>> t = fmtstr(u'asdf', 'blue', 'on_red', 'bold')
>>> x = fmtstr(u'asdf', 'green', 'on_red', 'bold')
>>> s = t + x
>>> s.ljust(10)
on_red(bold('asdfasdf  '))
```

**Comment by thomasballinger** [comment]
Added in master and 0.1.x.

**Comment by thomasballinger** [comment]
Thanks to @nfosterky for help with this! we paired on https://github.com/thomasballinger/curtsies/commit/f3e55e65bbdeff2f7c2a8b2f6b01558c6d368ea6
