### ISSUE TITLE
Context needed

### ISSUE THREAD

**Issue by pcgeek86** [thomasballinger/curtsies#81]
Not everyone who comes across this project is going to realize that this is a Python module. My suggestion would be to add "Python" to the GitHub project description, as well as the introduction to the project in your `readme.md` file.

> "Curtsies is a library for interacting with the terminal."

Should become something like ...

> "Curtsies is a Python 2.x & 3.x compatible library for interacting with the terminal."

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by thomasballinger** [comment]
Good point! This would be great to fix.
