### ISSUE TITLE
Documentation references removed module curtsies.terminal

### ISSUE THREAD

**Issue by Trundle** [thomasballinger/curtsies#93]
[Input.rst](https://github.com/thomasballinger/curtsies/blob/master/docs/Input.rst#input---events) says:

> To see what a given keypress is called (what unicode string is returned by Terminal.next()), try python -m curtsies.terminal and play around.

The problem is that `curtsies.terminal` was removed in 039832c9a99c415b9c8c91ba7274cca3c3416a28. I guess the mentioned command can be replaced with either `python -m curtsies.input` or `python -m curtsies.events`.

**Comment by thomasballinger** [comment]
@dputtick I know you were looking at some docfixes

**Comment by dputtick** [comment]
On it :)
