### ISSUE TITLE
examples/gameexample.py raises AttributeError

### ISSUE THREAD

**Issue by taotao54321** [thomasballinger/curtsies#95]
gameexample.py raises AttributeError on turn 20. Here is the traceback:

```
Traceback (most recent call last):
  File "gameexample.py", line 103, in <module>
    main()
  File "gameexample.py", line 96, in main
    msg = world.process_event(c)
  File "gameexample.py", line 55, in process_event
    return self.tick()
  File "gameexample.py", line 73, in tick
    self.player.display = on_blue(green(bold(str(self.player.speed).decode('utf8'))))
AttributeError: 'str' object has no attribute 'decode'
```

I think the call to decode() is not needed.

**Comment by ata2001** [comment]
@taotao54321 But removing decode() will break the compatibility with python2.

**Comment by thomasballinger** [comment]
Good catch, I just fixed in an ugly way with https://github.com/thomasballinger/curtsies/commit/c84f717720447f44377d2ff6b41766c542600fc1

I wonder if there's something more standard, maybe in six or something. Since it's not a dependency yet I'll go with this for now.
