### ISSUE TITLE
Could you support standard ANSI intensity format?

### ISSUE THREAD

**Issue by laike9m** [thomasballinger/curtsies#97]
According to https://en.wikipedia.org/wiki/ANSI_escape_code, one can add `;1` to display bright/bold text. But this currently doesn't work in bpython, instead, I have to prefix colored text with `\033[1m` to get bold effect.

<img width="311" alt="screen shot 2017-03-14 at 11 33 11 pm" src="https://cloud.githubusercontent.com/assets/2592205/23908348/bbd4a4b6-090e-11e7-8f4d-e037a0395bb7.png">

The inconsistency with standard ANSI escape code brings trouble to code that relies on it. Taking my current work [pdir2](https://github.com/laike9m/pdir2) as an example, [color](https://github.com/laike9m/pdir2/blob/master/pdir/constants.py#L189) can't be properly displayed in bpython.

I would like to know if you have plan to support this? I understand that it may conflicts with the current design/API, and it's totally ok if you don't.

**Comment by thomasballinger** [comment]
This is absolutely doable! I can't commit to doing it in the immediate future, but it's just some parsing code that needs to change.

**Comment by laike9m** [comment]
Sure. I'll find a workaround for now until you add this feature.

**Comment by thomasballinger** [comment]
If you want to hack it yourself or open a PR, check out https://github.com/thomasballinger/curtsies/blob/master/curtsies/escseqparse.py

**Comment by laike9m** [comment]
I think I'll just use a different kind of escape code for bpython, putting `\033[1m` in front.

**Comment by ata2001** [comment]
Created PR: #98.
